const tdoumasCreateRequest = {
  idlogin: "tdoumas",
  mdplogin: "123",
  nom: "Doumas",
  prenom: "Tristan",
  datenaissance: "1990-01-01",
  datedebutcontrat: "2022-01-01",
  fk_fonction: "Chauffeur",
  numtelephone: "1234567890",
  typepermis: "C",
  fk_adresse: 1,
  fk_decheterie: 1,
};

const tdoumasUpdateRequest = {
  idlogin: "tdoumas",
  mdplogin: "password",
  nom: "TriTri",
  prenom: "TriTri",
  datenaissance: "1990-01-01",
  datedebutcontrat: "2022-01-01",
  fk_fonction: "Chauffeur",
  numtelephone: "1234567890",
  typepermis: "C",
  fk_adresse: 1,
  fk_decheterie: 1,
};

const tdoumasGetOneResponse = {
  employesData: {
    idlogin: "tdoumas",
    nom: "Doumas",
    prenom: "Tristan",
    datenaissance: "1990-01-01",
    datedebutcontrat: "2022-01-01",
    numtelephone: "1234567890",
    typepermis: "C",
    fk_adresse: 1,
    fk_decheterie: 1,
    fk_fonction: "Chauffeur",
  },
};

const tdoumasGetAllResponse = {
  employesData: [
    {
      idlogin: "Resp1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: null,
      typepermis: null,
      fk_fonction: "Responsable",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Secr1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: "0123456789",
      typepermis: null,
      fk_fonction: "Secrétaire",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Empl1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: "0123456789",
      typepermis: null,
      fk_fonction: "Employé",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Chauff1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: null,
      typepermis: "C",
      fk_fonction: "Chauffeur",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "tdoumas",
      nom: "Doumas",
      prenom: "Tristan",
      datenaissance: "1990-01-01",
      datedebutcontrat: "2022-01-01",
      numtelephone: "1234567890",
      typepermis: "C",
      fk_adresse: 1,
      fk_decheterie: 1,
      fk_fonction: "Chauffeur",
    },
  ],
};

const jdoeCreateRequest = {
  idlogin: "jdoe",
  mdplogin: "123",
  nom: "Doumas",
  prenom: "Tristan",
  datenaissance: "1990-01-01",
  datedebutcontrat: "2022-01-01",
  fk_fonction: "Chauffeur",
  numtelephone: "1234567890",
  typepermis: "C",
  fk_adresse: 1,
  fk_decheterie: 2,
};

const jdoeUpdateRequest = {
  idlogin: "jdoe",
  mdplogin: "password",
  nom: "TriTri",
  prenom: "TriTri",
  datenaissance: "1990-01-01",
  datedebutcontrat: "2022-01-01",
  fk_fonction: "Chauffeur",
  numtelephone: "1234567890",
  typepermis: "C",
  fk_adresse: 1,
  fk_decheterie: 2,
};

const jdoeGetOneResponse = {
  employesData: {
    idlogin: "jdoe",
    nom: "Doumas",
    prenom: "Tristan",
    datenaissance: "1990-01-01",
    datedebutcontrat: "2022-01-01",
    numtelephone: "1234567890",
    typepermis: "C",
    fk_adresse: 1,
    fk_decheterie: 2,
    fk_fonction: "Chauffeur",
  },
};

const jdoeGetAllResponse = {
  employesData: [
    {
      idlogin: "Resp2",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: null,
      typepermis: null,
      fk_fonction: "Responsable",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Secr2",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: "0123456789",
      typepermis: null,
      fk_fonction: "Secrétaire",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Empl2",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: "0123456789",
      typepermis: null,
      fk_fonction: "Employé",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Chauff2",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: null,
      typepermis: "C",
      fk_fonction: "Chauffeur",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "jdoe",
      nom: "Doumas",
      prenom: "Tristan",
      datenaissance: "1990-01-01",
      datedebutcontrat: "2022-01-01",
      numtelephone: "1234567890",
      typepermis: "C",
      fk_adresse: 1,
      fk_decheterie: 1,
      fk_fonction: "Chauffeur",
    },
  ],
};

const dech1getAllResponse = {
  // get all decheterie 1 witout tdoumas
  employesData: [
    {
      idlogin: "Resp1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: null,
      typepermis: null,
      fk_fonction: "Responsable",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Secr1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: "0123456789",
      typepermis: null,
      fk_fonction: "Secrétaire",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Empl1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: "0123456789",
      typepermis: null,
      fk_fonction: "Employé",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
    {
      idlogin: "Chauff1",
      nom: "Nom",
      prenom: "Prenom",
      datenaissance: "2000-01-01",
      datedebutcontrat: "2020-01-01",
      numtelephone: null,
      typepermis: "C",
      fk_fonction: "Chauffeur",
      decheterie_nom: "Decheterie Yverdon",
      adresse_rue: "Rue 1",
      adresse_numero: "1",
      adresse_npa: "1400",
      adresse_nomville: "Yverdon-les-Bains",
      adresse_pays: "Suisse",
    },
  ],
};

export {
  tdoumasCreateRequest,
  tdoumasUpdateRequest,
  tdoumasGetOneResponse,
  tdoumasGetAllResponse,
  jdoeCreateRequest,
  jdoeUpdateRequest,
  jdoeGetOneResponse,
  jdoeGetAllResponse,
  dech1getAllResponse,
};
