name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: bitnami/postgresql:16
        # Provide the password for postgres
        env:
          POSTGRESQL_USERNAME: bdr
          POSTGRESQL_PASSWORD: bdr
          POSTGRESQL_DATABASE: bdr
          POSTGRESQL_POSTGRES_PASSWORD: root
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=10

        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        volumes:
          - ./db:/docker-entrypoint-initdb.d

    steps:
      - uses: actions/checkout@v4

      - name: Clone the secondary repository
        run:
          git clone
          https://github.com/PDG-GR9-Gestion-Decheterie/Gestion-Decheterie-Infra.git
          repo-temp

      - name: Move the db folder to the correct location
        run: mv repo-temp/release/db ./db

      - name: Clean up
        run: rm -rf repo-temp

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: npm ci
        working-directory: ./backend

      - run: npm run build --if-present
        working-directory: ./backend

      - run: npm test
        working-directory: ./backend

      - name: Display the contents of the database
        run: |
          echo "Displaying contents of the 'bdr' database:"
          PGPASSWORD=$POSTGRESQL_PASSWORD psql -U $POSTGRESQL_USERNAME -h localhost -d $POSTGRESQL_DATABASE -c "\dt"  # List tables
          PGPASSWORD=$POSTGRESQL_PASSWORD psql -U $POSTGRESQL_USERNAME -h localhost -d $POSTGRESQL_DATABASE -c "SELECT * FROM gestion_decheterie;"  # Replace <your_table_name> with the actual table name
        env:
          POSTGRESQL_USERNAME: bdr
          POSTGRESQL_PASSWORD: bdr
